service:
  name: codewars-api

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'main'}
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "*"
    - Effect: "Allow"
      Action: "events:*"
      Resource: "*"
  deploymentBucket:
    name: codewars-api-${opt:stage, 'main'}

custom:
  optimize:
    external: [
      'swagger-ui-dist',
      'debug',
      'ms',
      'pump',
      'once',
      'wrappy',
      'end-of-stream',
    ]

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors:
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
  import-user-data:
    handler: src/commands/import-user-data.command.handler
    events:
      - schedule: cron(15 0 * * ? *)

package:
  individually: true